on:
  push:
    branches:
      — master
  pull_request:
    branches:
      — master

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [macos-latest]
      runs-on: ${{ matrix.os }}

    steps:
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # Checks-out repository
      - name: Check-out repository
        uses: actions/checkout@v2

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go get github.com/gorilla/mux
          go get -u golang.org/x/lint/golint

      # Run lint on the code
      - name: Run lint
        run: golint .

      # Run testing on the code
      - name: Test
        run: go test -v ./...